# condense_wildcard_suffixes = true
edition = "2024"
# empty_item_single_line = true
# fn_single_line = true
# group_imports = "StdExternalCrate"
# imports_granularity = "Module"
match_block_trailing_comma = true
max_width = 120
merge_derives = true
remove_nested_parens = true
# reorder_impl_items = false
reorder_imports = true
reorder_modules = true
single_line_if_else_max_width = 120
# struct_field_align_threshold = 30
# struct_lit_single_line = true
tab_spaces = 2
use_field_init_shorthand = true
use_small_heuristics = "Max"
use_try_shorthand = true
# where_single_line = true
